### ISSUE TITLE
View Component

### ISSUE THREAD

**Issue by bohraji** [ColoredCow/laravel-dynamic-forms#3]
This package will utilise Blade and VueJS components to render components that will enable us to create, render and collect data in custom forms.
- [x] Setup blade components for creating form
- [x] Setup blade components to display form
- [x] Use VueJS resource to insert a form into the component to display dummy form.

**Comment by wevekamola** [comment]
@bohraji Will this package use the application utilities or we have add them in the package specifically like `bootstrap`, `vuejs`?

**Comment by bohraji** [comment]
@wevekamola It will be using application utilities. Can we add it as a dependency?

**Comment by wevekamola** [comment]
@bohraji Yeah I think we can add the required dependency in package's composer.json.
